---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloodbank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bloodbank.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: bloodbank-service #app-service.yml
              port:
                number: 80